# 0 - IMPORTS

In [3]:
import tensorflow as tf
import numpy as np
import warnings


warnings.filterwarnings('ignore')

# 1 - CREATE X, y VARIABLES

 X (in layer) and y (out layer) | One Layer Perceptron
:-:|:-:
![x_and_y](img/x_and_y.png) | ![x_and_y](img/1_layer_perceptron.png)

In [4]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [5]:
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

# 2 - CREATE WEIGHT TENSOR VARIABLE

In [6]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.variables.RefVariable

# 3 - CREATE ACTIVATION STEP FUNCTION

In [7]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

# 4 - CREATE OUTPUT LAYER

In [8]:
# multiplies input variable by weight variable
camada_saida = tf.matmul(X, W)

# 5 - CREATE ACTIVATION IN OUTPUT LAYER

In [9]:
camada_saida_ativacao = step(camada_saida)

Instructions for updating:
Use `tf.cast` instead.


# 6 - GET ERROR VALUE

In [10]:
erro = tf.subtract(y, camada_saida_ativacao)

# 7 - UPDATE WEIGHT VALUE

In [11]:
# peso(n +1) = peso(n) + ( taxa_aprendizagem * entrada * erro )

delta = tf.matmul(X, erro, transpose_a = True) # entrada * erro
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1))) # peso(n) + (delta * taxa_aprendizagem)

# 8 - RUN TENSORFLOW

In [12]:
init = tf.global_variables_initializer()

In [13]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(W))
    #print(sess.run(camada_saida))
    
    #print(sess.run(tf.to_float(tf.math.greater_equal(1, 1))))
    #print(sess.run(step(1)))
    #print('\n')
    #print(sess.run(camada_saida_ativacao))
    print('\n')
    #print(sess.run(erro))
    #print(X)
    #print('\n')
    #print(sess.run(tf.transpose(X)))
    #print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        #print(erro_total)
        print('Época:', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    W_final = sess.run(W)




Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  1.0
Época: 6  Erro:  0.0


In [14]:
W_final

array([[0.5],
       [0.5]])

In [15]:
# teste
camada_saida_teste = tf.matmul(X, W_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
